apiVersion: v1
kind: Service
metadata:
  name: hypershell-api-server-nodeport
  namespace: hypershell
spec:
  type: NodePort
  selector:
    app: hypershell-api-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
